services:
  web:
    build: src/GeoProject
    command:
      - /opt/geoappopt/.geoappvenv/bin/python3 /app/geoapp/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - '/opt/geoappopt/.geoappvenv'
      - '/app/geoapp'
