# Generated by Django 5.1.4 on 2025-01-11 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Giorgos', max_length=100)),
                ('query_city_1', models.CharField(default='', max_length=100)),
                ('query_city_2', models.CharField(default='', max_length=100)),
                ('coordinates_1', models.CharField(default='(0.0,0.0)', max_length=100)),
                ('coordinates_2', models.CharField(default='(0.0,0.0)', max_length=100)),
                ('result', models.FloatField(default=0.0)),
                ('fuel_consumption', models.FloatField(default=0.0)),
                ('calculated_distance', models.FloatField(default=0.0)),
                ('is_kilometers', models.BooleanField(default=True)),
                ('submition_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
